artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://figshare.com/ndownloader/files/53674172
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data

data_validation_config:
  clean_data_dir: clean_data
  credit_card_fraud_transaction_csv_file: credit_card_fraud_transactions.csv

feature_engineering_config:
  engineered_data_dir: engineered_data
  engineered_data_file: engineered_data.csv

model_training_config:
  model_dir: saved_models
  model_file: trained_model.cbm
  target_column: is_fraud